name: Allround
version: '${version}'
main: net.mira.allround.Allround
api-version: 1.19
authors: [ Miraibii ]
description: Plugin that makes fun fun fun

commands:
  sethome:
    description: Sets the home point of the player
    usage: /sethome
  home:
    description: Teleports the player to the home point
    usage: /home
  delhome:
    description: Delete your home
    usage: /delhome